select_origin: directory
files_origin: ./fiches
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: "./img"
export_target: ""
history: true
focus_max: 2
record_types:
  undefined:
    fill: "#858585"
    stroke: "#858585"
  personnage:
    fill: "#4B0082"
    stroke: "#4B0082"
  témoin:
    fill: "#FFD700"
    stroke: "#FFD700"
  lieu:
    fill: "#8B0000"
    stroke: "#8B0000"
  objet:
    fill: "#FFA500"
    stroke: "#FFA500"
  indice:
    fill: "#008000"
    stroke: "#008000"
  évènement:
    fill: "#483D8B"  
    stroke: "#483D8B"
  méthodologie:
    fill: "#2F4F4F"  
    stroke: "#2F4F4F"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
  o:
    stroke: simple
    color: "#FF0000"
  e:
    stroke: simple
    color: "#008000"
  a:
    stroke: simple
    color: "#1E90FF"
  c:
    stroke: simple
    color: "#FFD700"
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 14
graph_arrows: true
node_size_method: degree
node_size: 14
node_size_max: 25
node_size_min: 6
attraction_force: 200
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
chronological_record_meta: created
record_metas: []
title: Double meurtre dans la rue Morgue
author: Olivier Le Deuff
description: Le Graphe de la nouvelle d'Edgar Poe
keywords: []
link_symbol: 👉🏽
csl: ""
bibliography: ""
csl_locale: ""
css_custom: ./dupin.css
devtools: false
lang: fr
name: Double meurtre
